mesos-zk:
  image: bobrik/zookeeper
  ports:
   - 2181:2181
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

mesos-master:
  image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
  net: host
  environment:
    MESOS_ZK: zk://127.0.0.1:2181/mesos
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos

mesos-slave-one:
  image: mesosphere/mesos-slave:0.26.0-0.2.145.ubuntu1404
  net: host
  pid: host
  environment:
    MESOS_MASTER: zk://127.0.0.1:2181/mesos
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_PORT: 5051
    MESOS_RESOURCES: ports(*):[11000-11999]
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock

mesos-marathon:
  image: mesosphere/marathon:v0.14.0-RC1
  net: host
  environment:
    MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    MARATHON_DECLINE_OFFER_DURATION: 3600000
